var canvasHTML = document.getElementById('gameOfLifeCanvas');
var selectPatternHTML = document.getElementById('patternSelecteur');
var tailleEcran = [window.innerWidth, window.innerHeight];
var tailleSelecteurHTML = document.getElementById('tailleSelecteur');
var vitesseSelecteur = document.getElementById('vitesseSelecteur');
var infoStatsHTML = document.getElementById('infoStats');
var myAppInterval = 0;
var tempo = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var deplacementInterval = 0;
var toucheEnfonce = [];
var deplacementLibre = false;
var isPainting = false;
var shiftPressed = false;
var patternActuel;
var afficheTest = document.getElementById("fill");
var launcher = document.getElementById("launcher");
var jeu, canvas;